# マークダウン

In [1]:
import pandas as pd

In [4]:
import numpy as np
numpy.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [5]:
array = np.array([[1,2,3,4], [2,3,4,5], [3,4,5,6], [4,5,6,7]])
array

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [7]:
array[:2, :2]

array([[1, 2],
       [2, 3]])

In [9]:
np.arange(2,5,1)

array([2, 3, 4])

In [10]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(2,4)

array([[0.43445881, 0.6306456 , 0.13963477, 0.3787655 ],
       [0.32395566, 0.49924927, 0.64844747, 0.91395754]])